#!/usr/bin/env bash
# Display information about the records

get_string () {
    str=$(dig $1 | grep -A1 "ANSWER SECTION:" | tail -n 1)
}

if [ $# -eq 1 ]; then
    list="www lb-01 web-01 web-02"
    for subdomain in $list; do
	get_string "$subdomain.$1"
	echo "$str $subdomain" | awk '{ print "The subdomain " $6 " is a " $4 " record and points to " $5 }'
    done
else
    get_string "$2.$1"
    echo "$str $2" | awk '{ print "The subdomain " $6 " is a " $4 " record and points to " $5 }'
fi
