#!/usr/bin/env bash

# Backup the original hosts file
cp /etc/hosts /etc/hosts.bak

# Update localhost and facebook.com IP addresses
sed -i 's/127\.0\.0\.1/127\.0\.0\.2/' /etc/hosts
sed -i 's/157\.240\.11\.35/8\.8\.8\.8/' /etc/hosts

# Flush the DNS cache to apply the changes
systemd-resolve --flush-caches

echo "Changes applied successfully."

